name: Download k8s-snap

inputs:
  channel:
    description: k8s snap channel.
    type: string

outputs:
  snap-path:
    description: The *.snap destination path.
    value: ${{ steps.retrieve-path.outputs.snap-path }}

runs:
  using: "composite"
  steps:
    - name: Fail if channel is not specified
      if: inputs.channel == ''
      shell: bash
      run: |
        echo "No k8s-snap channel specified..."
        exit 1

    - name: Download snap channel
      if: inputs.channel != ''
      shell: bash
      run: |
        snap download k8s --channel=${{ inputs.channel }} --basename k8s
        full_path=`realpath k8s.snap`
        echo "Downloaded snap: $full_path"
        ls -lh $full_path

    - name: Retrieve resulting snap path
      shell: bash
      id: retrieve-path
      run: |
        snap_path="${{ github.workspace }}/k8s.snap"
        echo "snap-path=$snap_path" >> "$GITHUB_OUTPUT"

        echo "Output snap: $snap_path"
        ls -lh $snap_path
